### PR TITLE
Updated UI

### PR DESCRIPTION
**Pull request by deepesh611**
1. Updated `App.css`
2. Removed the empty `README.md` in `open-source-galaxy`

### CODE REVIEW

**Comment by Rupa-Rd** [comment]
Share a ss of the before and after

**Comment by deepesh611** [comment]
its the same ss that were used in our convo. Anyways, i'll add them again.

Before:
image

After:
image

**Comment by Rupa-Rd** [comment]
Some of the images are not visible entirely, J make sure to resize the images and make it responsive to various layouts

**Comment by deepesh611** [comment]
I have updated the PR @Rupa-Rd 

After:

image

**Comment by Rupa-Rd** [comment]
Is it responsive? 

> I have updated the PR @Rupa-Rd
> 
> After:
> 
> image

**Comment by deepesh611** [comment]
> Is it responsive?
> 
> > I have updated the PR @Rupa-Rd
> > After:
> > image



yes, it is

image

image

image

**Comment by Rupa-Rd** [comment]
Cool. Thanks for contributing. 🎉🎉
Looking for more from you!!

**Comment by deepesh611** [comment]
> Cool. Thanks for contributing. 🎉🎉 Looking for more from you!!

@Rupa-Rd, thank you, and pls make sure to update the score in discord

**Comment by Rupa-Rd** [comment]
closes #47

**Pull request merged**
