### PR TITLE
new changes to Login button and SearchBar

### PR DESCRIPTION
**Pull request by shatanshu3006**
closes issue number #22 
1. Adding border radius
2. Adding Hover effect
3. Adding a transition effect
4. The button goes a little darker and floats on hovering
5. Tooltips (hovering tip)
6. Similar hovering and Tooltips effect on Search Icon and Search Bar (with the same color changes [little darker])
7. Reduced the length of SearchBar
8. Aligned SearcBar,Search Icon and Login button with the Title of the Page ("Open Source Galaxy")
9. Faded the Placeholder and reduced the width 
10. Fade in animation for all three upon loading

Before:
Screenshot 2024-06-17 at 1 11 47 PM

After:
Screenshot 2024-06-17 at 1 12 08 PM

### CODE REVIEW

**Comment by Rupa-Rd** [comment]
Will it show any tooltips if I hover over it?

**Comment by shatanshu3006** [comment]
> Will it show any tooltips if I hover over it?

Yes all the three :

Screenshot 2024-06-17 at 1 49 25 PM

Screenshot 2024-06-17 at 1 49 43 PM

Screenshot 2024-06-17 at 1 50 02 PM

**Comment by Rupa-Rd** [comment]
Mention the issue number its closing, like 'closes #issuenumber'

**Comment by shatanshu3006** [comment]
> Mention the issue number its closing, like 'closes #issuenumber'

Done!

**Pull request merged**
