### PR TITLE
Solved Issue: Link opens in the same tab

### PR DESCRIPTION
**Pull request by akshhpatil**

### CODE REVIEW

**Comment by Rupa-Rd** [comment]
Could you add your Output ss and explain more on what you have done?

**Comment by akshhpatil** [comment]
The issue is that when the user clicks on a link, it opens in the same tab. This prevents the user from opening multiple Chrome tabs. As a result, the user has to go back to the home page and click on another link to open it.

image

So I have updated it. Now, when the user clicks on a link, it opens in another tab instead of the same tab.

OUTPUT

**Comment by Rupa-Rd** [comment]
Cool, are you doing this under VSOC?

**Comment by akshhpatil** [comment]
Yes

**Comment by Rupa-Rd** [comment]
Send your Email

**Comment by Rupa-Rd** [comment]
closes #62

**Pull request merged**
