### PR TITLE
Feat : Added some more open source programs

### LINKED ISSUE #60: [UI Design] Adding some more Open source programs
**Describe the solution you'd like**
We can add more opensource programs .

**Describe alternatives you've considered**

**Additional context**

@Rupa-Rd assign this to me i will add more open source programs . I am working under VSOC

### PR DESCRIPTION
**Pull request by Meetjain1**
Closes #60 

os1

email for VSOC meetofficialhere@gmail.com

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Rupa-Rd have a look on this PR. Thanks

**Comment by Rupa-Rd** [comment]
Would you make the images more rectangle like in the previous ?

> @Rupa-Rd have a look on this PR. Thanks

**Comment by Meetjain1** [comment]
> Would you make the images more rectangle like in the previous ?
> 
> > @Rupa-Rd have a look on this PR. Thanks

It is exact copy of the previous @Rupa-Rd 
I didn't change any thing in the styling

**Comment by Rupa-Rd** [comment]
> > Would you make the images more rectangle like in the previous ?
> > > @Rupa-Rd have a look on this PR. Thanks
> 
> It is exact copy of the previous @Rupa-Rd I didn't change any thing in the styling

I was referring to the image sizing. If you look closely, the newly added 3 event's images are in square shape. Except that everything is in rectangular that fits the border having top and bottom margin/padding. Kindly make the changes accordingly.

**Comment by Meetjain1** [comment]
> > > Would you make the images more rectangle like in the previous ?
> > > > @Rupa-Rd have a look on this PR. Thanks
> > 
> > 
> > It is exact copy of the previous @Rupa-Rd I didn't change any thing in the styling
> 
> I was referring to the image sizing. If you look closely, the newly added 3 event's images are in square shape. Except that everything is in rectangular that fits the border having top and bottom margin/padding. Kindly make the changes accordingly.

Got it sure @Rupa-Rd

**Comment by Meetjain1** [comment]
@Rupa-Rd done with these changes . Check it

**Comment by Meetjain1** [comment]
> @Rupa-Rd done with these changes . Check it

@Rupa-Rd ?

**Pull request merged**
