### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by deepesh611**
I have updated the README.md

Issue: https://github.com/Rupa-Rd/Open-Source-Galaxy/issues/44,  https://github.com/Rupa-Rd/Open-Source-Galaxy/issues/27

gmail: deepeshvcd6273@gmail.com

### CODE REVIEW

**Comment by Rupa-Rd** [comment]
@deepesh611 , who is @rofiesiiitp ?

**Comment by deepesh611** [comment]
> @deepesh611 , who is @rofiesiiitp ?

My apologies, I forgot to change my account in VS code. I assure u, i m the original editor.
*For Reference*:  @rofiesiiitp, is a github account of the robotics club of my college maintainer by me

account : https://github.com/rofiesiiitp
organization: https://github.com/ROFIES-IIITP

**Comment by Rupa-Rd** [comment]
Ok. but you cannot add both the github user in the readme

**Comment by deepesh611** [comment]
image
image
image

**Comment by deepesh611** [comment]
> Ok. but you cannot add both the github user in the readme

I don't intend to. again, My Apologies

**Comment by Rupa-Rd** [comment]
> > Ok. but you cannot add both the github user in the readme
> 
> I don't intend to. again, My Apologies

Good work! Looking forward you to contribute more!

**Comment by deepesh611** [comment]
also @Rupa-Rd, make sure to close the respective issues and update the score

email: deepeshvcd6273@gmail.com

**Pull request merged**
