### PR TITLE
adding an about page

### PR DESCRIPTION
**Pull request by mu6m**

### CODE REVIEW

**Comment by Rupa-Rd** [comment]
@mu6m Write a brief about the platform 'Open Source Galaxy' and what it is used for and what's the benefit. Also, change the background color provide more smooth animations for transitions.

**Comment by mu6m** [comment]
ok

**Comment by mu6m** [comment]
i will make the transitions needed but about writing i did write a brief about the platform in the about page

**Comment by mu6m** [comment]
@Rupa-Rd here it is i made a new commit

**Comment by mu6m** [comment]
please @Rupa-Rd can you merge it

**Comment by Rupa-Rd** [comment]
Cool, @mu6m Share your email asap

**Comment by mu6m** [comment]
theledraa@gmail.com

**Comment by Rupa-Rd** [comment]
@mu6m , kindly provide the vsoc registered email

**Comment by mu6m** [comment]
that's my main email,
what is vsoc?

**Pull request merged**
