### PR TITLE
Created an about section at the top

### PR DESCRIPTION
**Pull request by rajdesai17**
I added an about section above the opportunities card so that new visitors can have an idea about what Open Source galaxy is.
Screenshot 2024-06-25 153538

### CODE REVIEW

**Comment by Rupa-Rd** [comment]
@rajdesai17 Kindly follow the steps before raising a PR.
1. Create an issue with detailed description
2. Get the issued assigned to you
3. Work on the issue
4. Create a PR
5. Make changes and wait for the PR merge

**Comment by Rupa-Rd** [comment]
Kindly, create a new page for the About Us section. Since, there will be a button for About Us. And I'll keep this issue open once the header PR has been merged, do link the about us for the button
image

**Comment by Rupa-Rd** [comment]
Apologies for the confusion. @rajdesai17 And do mention the issue no as closes #issueno then I can be clear with the issue I've assigned to you.

> @rajdesai17 Kindly follow the steps before raising a PR.
> 
> 1. Create an issue with detailed description
> 2. Get the issued assigned to you
> 3. Work on the issue
> 4. Create a PR
> 5. Make changes and wait for the PR merge

**Comment by rajdesai17** [comment]
close issue no. #50 PR is opened.

**Comment by Rupa-Rd** [comment]
Have you done with this issue?


> close issue no. #50 PR is opened.

**Comment by rajdesai17** [comment]
conflicts solved, merge

**Pull request merged**
